apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::042020597064:role/udacity-node-group
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-07T14:20:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1041"
  uid: 9638fbdc-6a68-4e74-ae5b-110a941d2e2a
